[package]
name = "rust_gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.7"
chrono = "0.4.42"
dotenvy = "0.15.7"
redis = "1.0.1"
reqwest = "0.12.25"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
